name: vib-acc
dependencies:
- python 
- numpy>=1.20.3
- pytest
- pytest-cov
- flake8
- scipy
- pandas
- jupyter
- shapely
- pip
- pip:
  - pylife
  - tsfresh
  - spyder
  - spyder-unittest
  - pytorch-lightning
  - torch
  - trimesh>=3.9.19
  - rtree>=0.9.7
  - networkx>=2.5.1
  - matplotlib