name: vib-acc
dependencies:
- python 
- numpy>=1.20.2
- pytest
- pytest-cov
- flake8
- scipy
- pandas
- jupyter
- shapely
- pip
- pip:
  - pylife
  - tsfresh
  - spyder
  - spyder-unittest
<<<<<<< HEAD
  - pytorch>=1.7.1
  - pytorch-lightning>=1.3.0
=======
  - torch>=1.7.1
  - pytorch-lightning==1.3.4
>>>>>>> 4b13184c9ffa2017430092260942aced80c94d07
  - trimesh>=3.9.19
  - rtree>=0.9.7
  - networkx>=2.5.1
  - matplotlib>=3.4.2